function [stackedAEOptTheta]=final_finetune(stackedAETheta,layers,...
                                          numClasses,lambda,X, X_labels,options)
                                      
      [stackedAEOptTheta, loss] = minFunc( @(x) stackedAECost(x, ...
      layers, numClasses, lambda, X, X_labels), ...
      stackedAETheta, options);                             
end